apiVersion: v1
kind: Secret
metadata:
    name: wrprss-mysql
data: #data alanının içinde barındırılan değerler base64 ile kodlanmış şekilde barındırılmalıdır.
    mysql-root-password: IVBAc3N3MHJkMDEh #MySQL root parolası, root kullanıcısı ile erişim gerçekleştirildiğinde kullanılır.
    mysql-password: IURCUEByMGxhMDEh #Wordpress sitesi için özel üretilen parola
      # stringData alanının değerleri kodlanmamış şekilde kullanılabilir, her durumda, burada kullanılan değerler etcd'de kodlanmış şekilde saklanmakatadır.
stringData:
    mysql-username: dbroot
    mysql-rootuser: root 